version: "3"
services:
  app:
    build: 
      context: .
      dockerfile: Dockerfile
    depends_on:
      - postgres
    ports:
      - "3000:3000"

  postgres:
    image: postgres:11.2-alpine
    environment:
      POSTGRES_DB: shopdb
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: aaaaaa1
